W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  resource :session, only: [:create, :destroy, :new]
end

W4D5/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  live_album :boolean          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :year, :band_id, presence: true
  validates :live_album, :inclusion => {:in => [true, false]}

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band

  has_many :tracks,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: :Track,
    dependent: :destroy

  def album_type
    live_album ? "Live" : "Studio"
  end

end

W4D5/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :redirect_to_signup_if_not_logged_in

  def create #create new album
    @album = Album.new(album_params)
    band = @album.band
    if @album.save!
      redirect_to band_url(band)
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def new #show create new album page
    render :new
  end

  def edit #show edit album page
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def show #show individual album page
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def update #update existing album
    @album = Album.find_by(id: params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy #delete album
    @album = Album.find_by(id: params[:id])
    band = @album.band
    @album.destroy if @album
    redirect_to band_url(band)
  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :band_id, :live_album)
  end

end

W4D5/music_app/app/views/albums/edit.html.erb
<h2>This is the page for editing existing albums (from Album#edit)!</h2>


<form class="" action="<%= album_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Title</label>
    <input type="text" name="album[title]" id="title" value="<%= @album.title %>">
  <br/>

  <label for="year">Year</label>
    <input type="text" name="album[year]" id="year" value="<%= @album.year %>">
  <br/>

  <label for="band">Band</label>
    <select name="album[band_id]">
      <option disabled>Choose Band</option>
      <% bands = Band.all %>
      <% bands.each do |band| %>
        <option value="<%= band.id %>" <%= "selected" if @album.band == band %>><%= band.name %></option>
      <% end %>
    </select>
  <br/>

  <label for="album_type">Album Type</label>
    <input type="radio" name="album[live_album]" value="true" <%= "checked" if @album.live_album == true %>>Live<br>
    <input type="radio" name="album[live_album]" value="false" <%= "checked" if @album.live_album == false %>>Studio<br>
  <br/>

  <input type="submit" value="Update Album">
</form>

W4D5/music_app/app/views/albums/new.html.erb
<h2>This is the page for creating new albums (from Album#new)!</h2>


<form class="" action="<%= albums_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Title</label>
    <input type="text" name="album[title]" id="title" value="">
  <br/>

  <label for="year">Year</label>
    <input type="text" name="album[year]" id="year" value="">
  <br/>

  <label for="band">Band</label>
    <select name="album[band_id]">
      <option disabled>Choose Band</option>
      <% bands = Band.all %>
      <% bands.each do |band| %>
        <option value="<%= band.id %>" <%= "selected" if params[:band_id].to_i == band.id %>><%= band.name %></option>
      <% end %>
    </select>
  <br/>

  <label for="album_type">Album Type</label>
    <input type="radio" name="album[live_album]" value="true">Live<br>
    <input type="radio" name="album[live_album]" value="false">Studio<br>
  <br/>

  <input type="submit" value="Create Album">
</form>

W4D5/music_app/app/views/albums/show.html.erb
<h2>This is the page for displaying an existing album (Album#show)!</h2>

<p>Profile Page For <%= @album.title %></p>

<table>
  <tr>
    <th>Year</th><th><%= @album.year %></th>
  </tr>
  <tr>
    <th>Band</th><th><%= @album.band.name %></th>
  </tr>
  <tr>
    <th>Album Type</th><th><%= @album.album_type %></th>
  </tr>
  <tr>
    <th>Tracks</th><th><ul>
      <% tracks = @album.tracks %>
      <% if tracks.empty? %>
        <%= "This album has no tracks." %>
      <% else %>
        <% tracks.each do |track| %>
          <li><a href="<%= track_url(track) %>"><%= track.title %></a></li>
        <% end %>
      <% end %>
      <a href="<%= new_album_track_url(@album) %>">Add Track</a>
    </ul></th>
  </tr>
</table>

<a href="<%= edit_album_url %>">Edit Album</a>

<form class="" action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="submit" value="Delete Album">
</form>


<a href="<%= band_url(@album.band) %>">Back to Band</a>