W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  resource :session, only: [:create, :destroy, :new]
end

W4D5/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks,
    dependent: :destroy

end

W4D5/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :redirect_to_signup_if_not_logged_in
  
  def index #show all bands
    render :index
  end

  def create #create new band
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new #show create new band page
    render :new
  end

  def edit #show edit band page
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def show #show individual band page
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def update #update existing band
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy #delete band
    @band = Band.find_by(id: params[:id])
    @band.destroy if @band
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

W4D5/music_app/app/views/bands/edit.html.erb
<h2>This is the page for editing an existing bands (from Band#edit)!</h2>

<form class="" action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name">Name</label>
    <input type="text" name="band[name]" id="name" value="<%= @band.name %>">
  <br/>

  <input type="submit" value="Update Band">
</form>

W4D5/music_app/app/views/bands/index.html.erb
<h2>Band Index</h2>

<% bands = Band.all %>
<% bands.each do |band| %>
  <p><a href="<%= band_url(band) %>"><%= band.name %></a></p>
<% end %>

W4D5/music_app/app/views/bands/new.html.erb
<h2>This is the page for creating new bands (from Band#new)!</h2>


<form class="" action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name">Name</label>
    <input type="text" name="band[name]" id="name" value="">
  <br/>

  <input type="submit" value="Create Band">
</form>

W4D5/music_app/app/views/bands/show.html.erb
<section>
  <h2><%= @band.name %> Profile Page</h2>

  <form class="" action="<%= edit_band_url %>" method="get">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <input type="submit" value="Edit Band">
  </form>

  <form class="" action="<%= band_url(@band) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <input type="submit" value="Delete Band">
  </form>
</section>

<p>Albums</p>
<% albums = Album.where(band_id: @band.id)%>
<% if albums.empty? %>
  <%= "This band has no albums." %>
<% else %>
  <% albums.each do |album| %>
    <p><a href="<%= album_url(album) %>"><%= album.title %></a></p>
  <% end %>
<% end %>
<a href="<%= new_band_album_url(@band) %>">Add Album</a>